MLG.register("pieces", [
  {
    piece_id: "p001",
    title: "Mexican Hat Dance",
    catalog_number: "001",
    piece_folder: "001 Mexican Hat Dance",
    severity: "high",
    completeness_score: 62,
    completeness_tier: "partial",
    document_count: 2,
    page_count: 3,
    missing_required_count: 2,
    missing_required: [
      { label: "Tuba", canonical_instrument: "tuba", section: "Low Brass" },
      { label: "Snare Drum", canonical_instrument: "snare_drum", section: "Percussion" },
    ],
    has_expected_parts: true,
    instrumentation: [
      {
        part_index: 20,
        canonical_instrument: "flute",
        label: "Flute",
        section: "Woodwinds",
        required: true,
        present: true,
        documents: [{ doc_id: "e2b3c4d5e6f7a8b9", filename: "001 Mexican Hat Dance - Flute.pdf" }],
      },
      {
        part_index: 60,
        canonical_instrument: "baritone_bc",
        label: "Baritone BC",
        section: "Low Brass",
        required: true,
        present: true,
        documents: [{ doc_id: "d1a2b3c4d5e6f7a8", filename: "001 Mexican Hat Dance - Baritone BC.pdf" }],
      },
      {
        part_index: 62,
        canonical_instrument: "tuba",
        label: "Tuba",
        section: "Low Brass",
        required: true,
        present: false,
        documents: [],
      },
      {
        part_index: 80,
        canonical_instrument: "snare_drum",
        label: "Snare Drum",
        section: "Percussion",
        required: true,
        present: false,
        documents: [],
      },
    ],
    score: {
      has_score: false,
      score_missing: true,
      score_types: [],
      documents: [],
    },
    metadata: {
      composer: "Traditional (Mexico)",
      arranger: "F. Fennell",
      publisher: "Carl Fischer",
      year: 1948,
      summary:
        "\u201cJarabe Tapat\u00edo,\u201d popularly known as the Mexican Hat Dance, is Mexico\u2019s national folk dance, codified in the early 20th century. This concert-band setting pairs the tune\u2019s courtship rhythms with bright, dance-like scoring.",
    },
    instrumentation_source: {
      method: "authority_lookup",
      method_label: "Web lookup (authority source)",
      summary: "Identified by an LLM web search of authoritative publisher/catalog sources.",
      status: "matched",
      confidence: 0.82,
      model: "gpt-5",
      notes:
        "Matched the Carl Fischer concert-band edition arranged by Frederick Fennell. Instrumentation taken from the publisher's part list; baritone provided in BC only.",
      local_score_path: null,
      ocr_source: null,
      sources: [
        {
          title: "Carl Fischer \u2013 Mexican Hat Dance (concert band)",
          url: "https://www.carlfischer.com/",
          snippet: "Full concert band instrumentation with optional parts listed for the Fennell edition.",
        },
        {
          title: "Wind Repertory Project \u2013 Jarabe Tapat\u00edo",
          url: "https://www.windrep.org/",
          snippet: "Catalog entry confirming standard concert-band scoring and part breakdown.",
        },
      ],
    },
    thumbnail: null,
  },
  {
    piece_id: "p002",
    title: "Amazing Grace",
    catalog_number: "002",
    piece_folder: "002 Amazing Grace",
    severity: "ok",
    completeness_score: 95,
    completeness_tier: "complete",
    document_count: 1,
    page_count: 2,
    missing_required_count: 0,
    missing_required: [],
    has_expected_parts: false,
    instrumentation: [],
    score: {
      has_score: true,
      score_missing: false,
      score_types: ["full_score"],
      documents: [
        {
          doc_id: "f3c4d5e6f7a8b9c0",
          filename: "002 Amazing Grace - Full Score.pdf",
          pdf_path: "002 Amazing Grace/002 Amazing Grace - Full Score.pdf",
          score_type: "full_score",
        },
      ],
    },
    metadata: {
      composer: "Traditional",
      arranger: null,
      publisher: "Public Domain",
      year: 1779,
      summary:
        "\u201cAmazing Grace\u201d is a Christian hymn with words written in 1772 by English poet and clergyman John Newton, set to the folk melody \u201cNew Britain.\u201d It remains one of the most recognizable and widely arranged tunes in the English-speaking world.",
    },
    instrumentation_source: {
      method: "local_score_ocr",
      method_label: "OCR of local score",
      summary: "Read from the OCR'd text of the piece's own score.",
      status: "matched",
      confidence: 0.91,
      model: "gpt-5",
      notes:
        "Instrumentation read directly from the OCR'd full score included with the piece; all listed parts were present in the scan.",
      local_score_path: "002 Amazing Grace/002 Amazing Grace - Full Score.pdf",
      ocr_source: "local_score",
      sources: [],
    },
    thumbnail: null,
  },
]);
