MLG.register("documents", [
  {
    doc_id: "d1a2b3c4d5e6f7a8",
    piece_id: "p001",
    piece_title: "Mexican Hat Dance",
    pdf_filename: "001 Mexican Hat Dance - Baritone BC.pdf",
    pdf_path: "001 Mexican Hat Dance/001 Mexican Hat Dance - Baritone BC.pdf",
    instrument: "Baritone BC",
    section: "Low Brass",
    is_score: false,
    score_type: null,
    page_count: 2,
    quality: "fair",
    notation_source: "scan",
    legibility: "fair",
    ocr_status: "success",
    ocr_confidence: 0.82,
    vision_status: "success",
    vision_confidence: 0.74,
    thumbnail: null,
    first_text: "MEXICAN HAT DANCE\nBaritone B.C.\nArr. by ...",
    vision_notes: "Older photocopy; some staff lines faint in the lower system.",
  },
  {
    doc_id: "e2b3c4d5e6f7a8b9",
    piece_id: "p001",
    piece_title: "Mexican Hat Dance",
    pdf_filename: "001 Mexican Hat Dance - Flute.pdf",
    pdf_path: "001 Mexican Hat Dance/001 Mexican Hat Dance - Flute.pdf",
    instrument: "Flute",
    section: "Woodwinds",
    is_score: false,
    score_type: null,
    page_count: 1,
    quality: "good",
    notation_source: "printed",
    legibility: "good",
    ocr_status: "success",
    ocr_confidence: 0.94,
    vision_status: "success",
    vision_confidence: 0.9,
    thumbnail: null,
    first_text: "Mexican Hat Dance - Flute",
    vision_notes: "Clean printed engraving.",
  },
  {
    doc_id: "f3c4d5e6f7a8b9c0",
    piece_id: "p002",
    piece_title: "Amazing Grace",
    pdf_filename: "002 Amazing Grace - Full Score.pdf",
    pdf_path: "002 Amazing Grace/002 Amazing Grace - Full Score.pdf",
    instrument: "Full Score",
    section: "Score",
    is_score: true,
    score_type: "full_score",
    page_count: 2,
    quality: "good",
    notation_source: "printed",
    legibility: "good",
    ocr_status: "success",
    ocr_confidence: 0.96,
    vision_status: "success",
    vision_confidence: 0.92,
    thumbnail: null,
    first_text: "Amazing Grace\nFull Score\nTraditional",
    vision_notes: "High-quality digital engraving.",
  },
]);
